apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-server
  template:
    metadata:
      labels:
        app: data-server
    spec:
      containers:
      - name: api
        image: your-dockerhub-username/data_server_api_server_py:latest
        ports:
        - containerPort: 5555
        envFrom:
        - secretRef:
            name: data-server-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: data-server
spec:
  type: ClusterIP
  selector:
    app: data-server
  ports:
    - port: 5555
      targetPort: 5555 